### ISSUE TITLE
 umage-url is not registered

### ISSUE THREAD

**Issue by vlkalashnikov91** [HarryChen0506/react-markdown-editor-lite#196]
## OS and browser
For example, Windows 10, Chrome 80.0.

## Description
How it is necessary to create a function so that after the image is loaded, such a tag is formed
! [image-name] (**image-url**). The problem is that url is not being passed

## Reproduction URL
 [codesandbox](https://codesandbox.io/s/react-markdown-editor-lite-qwerty-forked-kzifr).

**Comment by HarryChen0506** [comment]
```
handleEditorChange = ({ html, text }) => {
    this.setState({ content: text });
};

onImageUpload = (file) => {
  return new Promise(resolve => {
    const reader = new FileReader();
    reader.onload = data => {
      resolve(data.target.result);
    };
    reader.readAsDataURL(file);
  });
};

```

1. Don't use replace `const newValue = text.replace(/\d/g, "");`
2. `onImageUpload` should be return a promise

**Comment by vlkalashnikov91** [comment]
> ```
> handleEditorChange = ({ html, text }) => {
>     this.setState({ content: text });
> };
> 
> onImageUpload = (file) => {
>   return new Promise(resolve => {
>     const reader = new FileReader();
>     reader.onload = data => {
>       resolve(data.target.result);
>     };
>     reader.readAsDataURL(file);
>   });
> };
> ```
> 
> 1. Don't use replace `const newValue = text.replace(/\d/g, "");`
> 2. `onImageUpload` should be return a promise

Thank you very much

**Comment by masaez** [comment]
@vlkalashnikov91 you got this working? I am having the same issue getting a "Can't perform a React state update on an unmounted component" warning. I have the impression that the issue is related to the use of default values, since its the common thing I see between your sample and my code. I am trying to perform S3 uploads of the pictures, and the URLs don't get passed to the Markdown box either
